spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:kream;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  config: classpath:logback-${spring.profiles.active}.xml
