= KREAM API 문서
:doctype: book
:icons: front
:source-highlighter: highlightjs
:toc: left
:sectnums:
:toclevels: 2

[[Brand]]
== 브랜드 API

[[find-all-brands]]
=== 브랜드 전체 조회
해당 API의 경우 존재하는 모든 브랜드를 조회하는 경우 사용하는 API입니다.

operation::find-all-brands[snippets = 'http-request,http-response']

[[find-brand-by-id]]
=== 단일 브랜드 조회
해당 API의 경우 브랜드의 Id로 브랜드를 조회하는 경우 사용하는 API입니다.

operation::find-brand-by-id[snippets = 'http-request,http-response']

[[save-brand]]
=== 브랜드 등록
해당 API의 경우 브랜드를 등록하는 경우 사용하는 API입니다.

operation::save-brand[snippets = 'http-request,http-response']

== 구매 입찰 API
include::api/purchasebidding/purchase-bid-select-view.adoc[]

[[Product-API]]
== 상품 API

[[find-all-products]]
=== 상품 전체 조회
해당 API의 경우 존재하는 상품을 모두 조회하는 경우 사용하는 API입니다.

operation::find-all-products[snippets = 'http-request,http-response']

[[save-product]]
=== 상품 등록
해당 API의 경우 상품을 등록하는 경우 사용하는 API입니다.

operation::save-product[snippets = 'http-request,http-response']

[[update-product-by-id]]
=== 상품 수정
해당 API의 경우 상품을 수정하는 경우 사용하는 API입니다.

operation::update-product-by-id[snippets = 'http-request,http-response']]

[[Bidding-Sell]]
== 판매 입찰 API

[[Bidding-Sell-Get]]
=== 판매 입찰 페이지 조회

operation::get-prodcut-information[snippets = 'http-request,http-response']

[[Bidding-Sell-Enroll]]
=== 판매 입찰 등록
해당 API의 경우 판매하려는 품목에 대해서 구매 입찰 건이 없거나 판매자가 원하는 금액으로 팔려고 하는 경우 사용하는 API입니다.

operation::save-sell-bidding[snippets = 'http-request,http-response']

[[Bidding-Sell-Transact]]
=== 즉시 판매
해당 API의 경우 판매하려는 품목에 대해 이미 올라온 구매 입찰 건에 대해서 거래를 체결하려고 하는 경우 사용하는 API입니다.

operation::transact-purchase-bidding[snippets = 'http-request,http-response']
